# Base theme: https://github.com/jekyll/minima

title: ⚓️ Webhook.site
author: © Simon Fredsted
description: ""
baseurl: ""
url: ""

logo: logo.png

aux_links:
  "Github": "//github.com/fredsted/webhook.site"  
  "Support": "//support.webhook.site"
  "Back to Webhook.site": "//webhook.site"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
