# Base theme: https://github.com/jekyll/minima

title: ⚓️ Webhook.site
author: © Simon Fredsted
description: ""
baseurl: ""
url: ""

logo: logo.png

aux_links:
  "Edit Page": "https://github.com/fredsted/webhook.site/tree/gh-pages"
  "Github": "//github.com/fredsted/webhook.site"  
  "Support": "//support.webhook.site"
  "Back to Webhook.site": "//webhook.site"

source: _pages

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
#   - jekyll-feed
