site_name: Webhook.site Docs
site_url: https://docs.webhook.site

theme:
  name: material
  logo: images/icon.png
  favicon: images/favicon.ico
  features:
    - navigation.expand
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fredsted/webhook.site
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/webhooksite
  
use_directory_urls: false

plugins:
  - search
  - redirects:
      redirect_maps:
        'webhookscript.md': webhookscript/index.markdown
        'api.md': api/about.md

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - attr_list
  
extra_css:
  - stylesheets/extra.css
  
nav:
  - About: index.markdown
  - News & Changelog: news.markdown
  - Open Source version: open-source.markdown
  - CLI: cli.md
  - API:
    - Usage & Authentication: api/about.md
    - Script Examples: api/examples.md
    - Tokens (URLs/Email addresses): api/tokens.md
    - Custom Actions: api/custom-actions.md
    - Schedules: api/schedules.md
  - Webhook.site Pro and Enterprise: pro.markdown
  - FAQ: faq.markdown
  - Schedules: schedules.md
  - Custom Actions:
    - About Custom Actions: custom-actions.markdown
    - Action Types: custom-actions/action-types.md
    - Examples: custom-actions/examples.markdown
  - WebhookScript:
    - About WebhookScript: webhookscript/index.markdown
    - Examples: webhookscript/examples.markdown
    - Reference: webhookscript/reference.markdown
    - Built-in Functions:
      - General: webhookscript/functions/general.md
      - Arrays: webhookscript/functions/array.md
      - Booleans: webhookscript/functions/bool.md
      - Dates: webhookscript/functions/date.md
      - File handling: webhookscript/functions/files.md
      - Flow Control and Responses: webhookscript/functions/flow.md
      - Math and Numbers: webhookscript/functions/math.md
      - Network and HTTP: webhookscript/functions/network.md
      - Strings: webhookscript/functions/string.md
      - Custom Action Variables: webhookscript/functions/variables.md
  - ← Back to Webhook.site: https://webhook.site  
