site_name: Webhook.site Docs

theme:
  name: material
  logo: images/icon.png
  favicon: images/favicon.ico
  features:
    - navigation.expand
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fredsted/webhook.site
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fredsted
  
use_directory_urls: false

plugins:
  - search
  - redirects:
      redirect_maps:
        'webhookscript.md': webhookscript/index.markdown

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  
extra_css:
  - stylesheets/extra.css
  
nav:
  - About: index.markdown
  - News & Changelog: news.markdown
  - Install: install.markdown
  - API: api.markdown
  - Premium: premium.markdown
  - Schedules: schedules.md
  - Custom Actions: custom-actions.markdown
  - WebhookScript:
    - About WebhookScript: webhookscript/index.markdown
    - Reference: webhookscript/reference.markdown
    - Examples: webhookscript/examples.markdown
    - Functions: webhookscript/functions.markdown
  - ← Back to Webhook.site: https://webhook.site  
